### ISSUE TITLE
If process.env.NODE_ENV is "production" then pass through unchanged

### ISSUE THREAD

**Issue by jaredly** [gajus/react-strict-prop-types#1]
Would be nice to have this incur no perf costs in prod

**Comment by gajus** [comment]
I am not a fan using global/process variable in the code. I think a lot more sensible solution would be to have an option "disable", that when `true` would return the original component. That way, you could have:

``` js
@StrictPropTypes({disable: process.env.NODE_ENV === 'production'})
export default class extends React.Component {
    render () {
        return <div />;
    }
}
```

What do you think?

**Comment by jaredly** [comment]
:/ and then you'd have that everywhere? a lot more noisy than I'd like.

On the other hand, I can just use my own wrapper

``` js
// my-enforce-props.js
import StrictPropTypes from "yyy";

export default function (Component) {
  if (process.env.NODE_ENV === 'production') {
    return Component;
  }
  return StrictPropTypes(Component);
}
```

**Comment by gajus** [comment]
Thank you. I have documented this suggestion in the README. https://github.com/gajus/react-strict-prop-types#production-mode

**Comment by panayi** [comment]
If you are using a webpack, I wrote a loader for preprocessing a file and exporting a `react-strict-prop-types` HOC, when an `export default MyComponent` is found at the end of file:

``` javascript
/**
 * Composes a higher-order-component with react-strict-prop-types, given that:
 * 1) The export is in the format `export default yourComponentNameHere`,
 * 2) The export statement is the last statement in the file,
 * 3) `yourComponentNameHere` contains only [a-zA-Z0-9_-].
 *
 * @see https://github.com/gajus/react-strict-prop-types
 *
 * @example
 * // Webpack configuration
 * var config = {
 *   module: {
 *     preLoaders: [
 *       { test: /\/[A-Z][^\/]*\.(js|jsx)?$/, loader: 'react-strict-props', exclude: /node_modules/ }
 *       // ... other loaders
 *     ]
 *   }
 * }
 *
 * // Add "?debug" for logging warnings when no valid export statement was found:
 * { test: /\/[A-Z][^\/]*\.(js|jsx)?$/, loader: 'react-strict-props?debug', exclude: /node_modules/ }
 */
module.exports = function(source) {
  var regex = /export +default +([\w-]+)([\n;]*)$/;
  var debug = this.query.indexOf('debug') > -1;

  this.cacheable();

  if (regex.test(source)) {
    source = source.replace(regex, 'export default StrictPropTypes($1)$2');
    source = 'import StrictPropTypes from \'react-strict-prop-types\'\n' + source;
  } else if (debug) {
    console.log('\x1b[33mWARNING in ' + this.resourcePath + '\n' +
        'A valid export statement for react-strict-props loader was not found\x1b[0m');
  }

  return source;
}
```

**Comment by gajus** [comment]
@panayi From the reliability/maintainability perspective, I think this would better as a babel plugin.

Thank you for sharing.

**Comment by panayi** [comment]
In the end the above loader is not much use - when constructing additional HOC it applies strict-prop-types to that, which makes it impossible to define the missing propTypes. So I've quit using the loader, and now using a similar approach to https://github.com/gajus/react-strict-prop-types/issues/1#issuecomment-136471681.

**Comment by panayi** [comment]
Another suggestion is to provide an option for disabling strict-prop-types. Something like (https://github.com/gajus/react-strict-prop-types/blob/master/src/index.js#L14):

``` javascript
functionConstructor = (Component, options = {}) => {
    return options.disabled ? Component : strictPropTypes(Component, options);
};
```

And use it as:

``` javascript
@StrictPropTypes({ disabled: process.env.NODE_ENV === 'production' })
export default class MyComponent extends React.Component {

}
```

**Comment by panayi** [comment]
Oops, just realized the exact same suggestion is above :). Ignore. IMO [this](https://github.com/gajus/react-strict-prop-types/issues/1#issuecomment-136465640) is useful, and the developer can choose to opt out, and instead use a wrapper.
