### ISSUE TITLE
camelCasing allowed HTML props

### ISSUE THREAD

**Issue by quantizor** [gajus/react-strict-prop-types#2]
React requires camel-casing of certain HTML attribute names: https://facebook.github.io/react/docs/tags-and-attributes.html

Looks like there are a bunch in https://github.com/gajus/react-strict-prop-types/blob/master/src/HTMLPropNames.js that need to be adjusted, otherwise React will ignore them.

**Comment by gajus** [comment]
This is done in the 0.6.1 version. I have added SVG support too. https://github.com/gajus/react-strict-prop-types/tree/0.6.1

**Comment by gajus** [comment]
Thank you! @yaycmyk
